var blocks = document.querySelector("#blocks");

var link = ["spaghetti", 
    "tortilla", 
    "spaghetti-tonno", 
    "kasza-z-sosem-miesnym", 
    "klopsy-ziemniaki-mizeria", 
    "kaszotto", 
    "nalesniki", 
    "chilli-con-carne", 
    "puree-jajko-kalafior", 
    "kluski-na-parze", 
    "jajko-fasolka-kalafioroweklopsy", 
    "rosol", 
    "golabki", 
    "pulpety-ziemniaki-ogorek", 
    "carbonara", 
    "makaron-losos-brokul", 
    "fasolka-ziemniaki-filet", 
    "leczo", 
    "losos-tabbouleh", 
    "potrawka-warzywna", 
    "racuchy", 
    "makaron-papryka-kielbasa-jajko", 
    "zapiekanka-kasza", 
    "kluski-serowe", 
    "coleslaw-ziemniaki-indyk", 
    "fasolka-po-bretonsku", 
    "zur", 
    "ryz-sos-miesny", 
    "gulasz", 
    "pyzy", 
    "kluski-rolada-kapusta", 
    "burrito", 
    "zapiekanka", 
    "zapiekanka-ziemniaki", 
    "lazania", 
    "krokiety", 
    "kociolek", 
    "zapiekanka-makaron", 
    "ryz-jablko-cynamon", 
    "gesty-groszek-marchewka-ziemniaki-filet", 
    "pierogi", 
    "bigos", 
    "ryz-warzywa", 
    "filet-brokul-ziemniaki", 
    "kalafior-jajko-ziemniak", 
    "losos-ziemniaki-surowka", 
    "kurczak-ciasto-francuskie", 
    "kotlet-ziemniaki-surowka", 
    "makaron-ala-lasagna", 
    "ziemniaki", 
    "kuskus", 
    "salatka-penne",
    "ryz-kurczak",
    "kurczak-ziemniaki-surowka",
    "makaron-twarog",
    "ryz-kurczak-papryka",
    "indyk-ziemniaki-surowka",
    "gyros",
    "pastisio",
    "surowka-wiosenna",
    "makaron-kurczak-sos-smietana-pomidor",
    "ryz2",
    "pancakes",
    "owsianki-nocne",
    "grysik"];

var nazwa = ["spaghetti", 
    "tortilla", 
    "spgahetti tonno", 
    "kasza z sosem mięsnym", 
    "klopsy z ziemniakami i mizerią", 
    "kaszotto", 
    "naleśniki", 
    "chilli con carne", 
    "puree, jajko i kalafior", 
    "kluski na parze", 
    "jajko z fasolką i kalafiorowymi klopsami", 
    "rosół", 
    "gołąbki", 
    "pulpety z sosem, ziemniakami i ogórkami kiszonymi", 
    "carbonara", 
    "makaron z łososiem i brokułem", 
    "fasolka, ziemniakami i filet", 
    "leczo", 
    "łosoś, tabbouleh(libańska sałatka)", 
    "potrawka warzywna", 
    "racuchy", 
    "makaron z papryką, kiełbasą i jajkiem", 
    "zapiekanka z kaszy", 
    "kluski serowe", 
    "colesław,ziemniaki i indyk", 
    "fasolka po bretońsku", 
    "żurek", 
    "ryż z sosem mięsnym", 
    "gulasz", 
    "pyzy", 
    "kluski śląskie, rolada i fioletowa kapusta", 
    "burrito", 
    "zapiekanki", 
    "zapiekanka z ziemniaków", 
    "lazania", 
    "krokiety", 
    "kociołek", 
    "zapiekanka z makaronu", 
    "ryż z jabłkiem i cynamonem", 
    "gęsty groszek i marchewka z ziemniakami i filetem", 
    "pierogi", 
    "bigos", 
    "ryż z warzywami", 
    "filet, brokuł, ryż/ziemniaki", 
    "kalafior, ziemniaki i jajko z bułką tartą", 
    "łosoś, ziemniaki i surówka z kapusty kiszonej", 
    "kurczak w cieście francuskim", 
    "kotlet z ziemniakami i surówką wiosenną", 
    "makaron z sosem ala lasagna i kurczak", 
    "ziemniaki szybkowar", 
    "sałatka kuskus", 
    "sałatka z penne, mozarellą i pomidorem",
    "ryż z gotowanym kurczakiem",
    "kurczak z pieca z ziemniakami i surówką wiosenną",
    "makaron z twarogiem",
    "ryż z kurczakiem i papryką",
    "pierś z indyka z ziemniakami i surówką",
    "gyros",
    "pastisio",
    "surówka wiosenna",
    "makaron z kurczakiem i sosem śmietanowo-pomidorowym",
    "ryż",
    "pancakes",
    "owsianki nocne",
    "grysik"];

var tagi = [/*spaghetti*/"makaron mieso", 
    /*tortilla*/"mieso wege ryba szybkie", 
    /*spgahetti tonno*/"makaron ryba szybkie", 
    /*kasza z sosem mięsnym*/"kasza mieso szybkie", 
    /*klopsy z ziemniakami i mizerią*/"ziemniaki surowki x3 mieso", 
    /*kaszotto*/"kasza wege", 
    /*naleśniki*/"slodkie wege", 
    /*chilli con carne*/"ryz mieso szybkie", 
    /*puree, jajko i kalafior*/"ziemniaki x3 wege", 
    /*kluski na parze*/"wege slodkie szybkie kluski", 
    /*jajko z fasolką i kalafiorowymi klopsami*/"wege x3", 
    /*rosół*/"zupy mieso", 
    /*gołąbki*/"szybkie mieso ryz", 
    /*pulpety z sosem, ziemniakami i ogórkami kiszonymi*/"mieso ziemniaki x3", 
    /*carbonara*/"makaron szybkie", 
    /*makaron z łososiem i brokułem*/"makaron ryba szybkie", 
    /*fasolka, ziemniakami i filet*/"ziemniaki x3 mieso", 
    /*leczo*/"zupy mieso ryz", 
    /*łosoś, tabbouleh(libańska sałatka)*/"ryba kasza surowki x3", 
    /*potrawka warzywna*/"zupy wege ziemniaki", 
    /*racuchy*/"slodkie szybkie wege", 
    /*makaron z papryką, kiełbasą i jajkiem*/"makaron mieso szybkie", 
    /*zapiekanka z kaszy*/"zapiekanki kasza mieso piekarnik", 
    /*kluski serowe*/"kluski slodkie wege", 
    /*colesław,ziemniaki i indyk*/"surowki mieso ziemniaki x3", 
    /*fasolka po bretońsku*/"zupy mieso", 
    /*żurek*/"zupy ziemniaki wege", 
    /*ryż z sosem mięsnym*/"mieso ryz szybkie", 
    /*gulasz*/"mieso kasza", 
    /*pyzy*/"kluski mieso szybkie", 
    /*kluski śląskie, rolada i fioletowa kapusta*/"kluski surowki mieso", 
    /*burrito*/"szybkie mieso ryz", 
    /*zapiekanki*/"zapiekanki piekarnk mieso ryba wege szybkie", 
    /*zapiekanka z ziemniaków*/"ziemniaki mieso piekarnik zapiekanki", 
    /*lazania*/"makaron mieso piekarnik", 
    /*krokiety*/"mieso", 
    /*kociołek*/"ziemniaki mieso zapiekanki piekarnik", 
    /*zapiekanka z makaronu*/"makaron zapiekanki piekarnik", 
    /*ryż z jabłkiem i cynamonem*/"ryz wege szybkie slodkie", 
    /*gęsty groszek i marchewka z ziemniakami i filetem*/"x3 ziemniaki mieso surowki", 
    /*pierogi*/"kluski mieso", 
    /*bigos*/"zupy mieso", 
    /*ryż z warzywami*/"ryz mieso szybkie", 
    /*filet, brokuł, ryż/ziemniaki*/"ryz ziemniaki mieso x3", 
    /*kalafior, ziemniaki i jajko z bułką tartą*/"wege ziemniaki x3", 
    /*łosoś, ziemniaki i surówka z kapusty kiszonej*/"ryba x3 ziemniaki surowki", 
    /*kurczak w cieście francuskim*/"mieso piekarnik", 
    /*kotlet z ziemniakami i surówką wiosenną*/"x3 mieso ziemniaki surowki", 
    /*makaron z sosem ala lasagna i kurczak*/"makaron mieso", 
    /*ziemniaki szybkowar*/"ziemniaki", 
    /*sałatka kuskus*/"ryba kasza surowki szybkie", 
    /*sałatka z penne, mozarellą i pomidorem*/"makaron wege surowki szybkie",
    /*ryż z gotowanym kurczakiem*/"ryz mieso",
    /*kurczak z pieca z ziemniakami i surówką wiosenną*/"mieso ziemniaki surowki x3",
    /*makaron z twarogiem*/"makaron wege slodkie szybkie",
    /*ryż z kurczakiem i papryką*/"ryz mieso",
    /*pierś z indyka z ziemniakami i surówką*/"mieso x3 ziemniaki surowki",
    /*gyros*/"surowki mieso",
    /*pastisio*/"makaron mieso piekarnik",
    /*surówka wiosenna*/"surowki wege",
    /*makaron z kurczakiem i sosem śmietanowo-pomidorowym*/"makaron mieso szybkie",
    /*ryż*/"ryz",
    /*pancakes*/"wege slodkie szybkie",
    /*owsianki nocne*/"szybkie wege slodkie",
    /*grysik*/"szybkie slodkie wege kasza"];

for (let i = 0; i < nazwa.length; i++) {

    var html = blocks.innerHTML += "<figure id='" + link[i] + "' class='" + tagi[i] + "'><a href='recipe/" + link[i] + ".html'><img src='img/" + link[i] + ".jpg' alt='" + nazwa[i] + "'></a><figcaption>" + nazwa[i] + "</figcaption>"
}

//rosół 60g makaronu na 1 osobę